export const constant = {
    URL_API: "https://immense-shelf-19793.herokuapp.com/api",
    SUCCESS: "SUCCESS",
    FAILURE: "FAILURE",
    LOADING: "LOADING",
    // homeinfo
    GET_HOMEINFO_SUCCESS: "GET_HOMEINFO_SUCCESS",
    GET_HOMEINFO_FAILURE: "GET_HOMEINFO_FAILURE",
    // category
    GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
    GET_CATEGORY_FAILURE: "GET_CATEGORY_FAILURE",
    // product
    GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
    GET_PRODUCTS_FAILURE: "GET_PRODUCTS_FAILURE",
    GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
    GET_PRODUCT_FAILURE: "GET_PRODUCT_FAILURE",
    GET_PRODUCT_SIMILAR_SUCCESS: "GET_PRODUCT_SIMILAR_SUCCESS",
    GET_PRODUCT_SIMILAR_FAILURE: "GET_PRODUCT_SIMILAR_FAILURE",
}