export const constant = {
    URL_API: "https://immense-shelf-19793.herokuapp.com/api",
    SUCCESS: "SUCCESS",
    FAILURE: "FAILURE",
    LOADING: "LOADING",
    // category
    GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
    GET_CATEGORY_FAILURE: "GET_CATEGORY_FAILURE",
    // product
    GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
    GET_PRODUCTS_FAILURE: "GET_PRODUCTS_FAILURE",
}